#!/bin/bash
# Xcode Build Phase script — ngrok URL'ini otomatik çeker ve NgrokURL.swift dosyasına yazar.
# Mac üzerinde çalışır (build time), iPhone bu dosyanın sonucunu kullanır.

OUTPUT_FILE="${SRCROOT}/MenuLo/Utilities/NgrokURL.swift"

# ngrok local API'den aktif HTTPS tunnel URL'ini al
NGROK_URL=$(curl -s --max-time 2 http://127.0.0.1:4040/api/tunnels 2>/dev/null | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    for t in data.get('tunnels', []):
        if t.get('proto') == 'https':
            print(t['public_url'])
            sys.exit(0)
    # HTTPS yoksa ilk tunnel
    tunnels = data.get('tunnels', [])
    if tunnels:
        print(tunnels[0]['public_url'])
except:
    pass
" 2>/dev/null)

if [ -z "$NGROK_URL" ]; then
    echo "⚠️ Ngrok bulunamadı, localhost kullanılıyor"
    BASE_URL="http://localhost:3000/api"
else
    echo "🌐 Ngrok tunnel bulundu: ${NGROK_URL}"
    BASE_URL="${NGROK_URL}/api"
fi

# Swift dosyasını oluştur/güncelle
cat > "$OUTPUT_FILE" << EOF
// Auto-generated by fetch_ngrok_url.sh — elle düzenleme!
// Build zamanı: $(date)
import Foundation

enum NgrokConfig {
    static let baseURL = "${BASE_URL}"
}
EOF

echo "✅ NgrokURL.swift güncellendi: ${BASE_URL}"
